- name: Install Teams for Linux
  hosts: devs
  become: true
  vars:
    teams_snap_name: teams-for-linux

  tasks:
    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: true

    - name: Ensure snapd service is running
      ansible.builtin.service:
        name: snapd
        state: started
        enabled: true

    - name: Check Teams for Linux snap installation
      ansible.builtin.command:
        cmd: "snap list {{ teams_snap_name }}"
      register: teams_snap
      changed_when: false
      failed_when: false

    - name: Install Teams for Linux snap
      ansible.builtin.command:
        cmd: "snap install {{ teams_snap_name }}"
      changed_when: true
      when: teams_snap.rc != 0
