- name: Update hosts
  import_playbook: ../playbooks/update/playbook.yaml
- name: Install Teams
  import_playbook: ../playbooks/teams/playbook.yaml
- name: Install Google Chrome
  import_playbook: ../playbooks/google-chrome/playbook.yaml
