- name: Update hosts
  import_playbook: ../playbooks/update/playbook.yaml
- name: Configure Ansible user SSH access
  import_playbook: ../playbooks/ansible-user/playbook.yaml
- name: Configure end user
  import_playbook: ../playbooks/user/playbook.yaml
- name: Install base packages
  import_playbook: ../playbooks/base-packages/playbook.yaml
- name: Install keyd
  import_playbook: ../playbooks/keyd/playbook.yaml
- name: Install Zsh
  import_playbook: ../playbooks/zsh/playbook.yaml
- name: Install GNOME Clipboard Indicator
  import_playbook: ../playbooks/gnome-clipboard-indicator/playbook.yaml
- name: Install Keeper Password Manager
  import_playbook: ../playbooks/keeper/playbook.yaml
- name: Install Google Chrome
  import_playbook: ../playbooks/google-chrome/playbook.yaml
